### PR TITLE
Updated the Cinder-0.8.6 branch with the glNext changes

### PR DESCRIPTION
**Pull request by hluisi**
Hi simongeilfus,
I took the new changes from the glNext branch and converted them back to 0.8.6 for a project I'm working on...  So I thought I'd send you a pull request just in case you wanted to update your Cinder-0.8.6 branch.  I also added a setThemeColor to the Options struc to make it a bit easier to change the theme colors.  Anyway, its here if you want them.  And thanks for the cinder block! 

Hunter

### CODE REVIEW

**Comment by simongeilfus** [comment]
Hey thanks a lot for this,

I've moved to gl_next and not looked back since, so the 0.8.6 branch was a bit abandoned! I quickly had a look to your changes and it looks good to me.

About the setThemeColors function, I totally removed it locally, it didn't made so much sense to keep this anymore. I think your approach is probably better. We should maybe simplify even more by renaming those "setThemeColor" to only "color":

```c++
        //! specifies a color
        Options& color( ImGuiCol_ option, const ImVec4 &v ) ;
        Options& color( ImGuiCol_ option, const ci::ColorA &v ) ;
```

**Comment by simongeilfus** [comment]
I just saw you commented the implicit cast operators. I remember having trouble with them in an earlier version of this block, but can't remember on what platform. It works fine on osx on the master branch... Are you on windows?

**Comment by hluisi** [comment]
Yes I'm on windows and for some some reason the defines won't take.  I'm sure its something simple but I gave up on it after an messing with it for an hour or so.  But sure I'll simplify the Options color and try putting the casts back.

**Comment by hluisi** [comment]
Ha I'm an idiot, lol.  At some point I put CINDER_IMGUI_NO_IMPLICIT_CASTS in my Debug preprocessor definitions.  Changes made, push incoming.

**Comment by hluisi** [comment]
Everything should be good now.  Does this work for you?

**Comment by ocornut** [comment]
Would be nice to merge that in and advertise the old branch a little. I'm talking to a guy who had the exact same issue and working with 0.8.6 and struggled with updating.

**Comment by brucelane** [comment]
+1

**Comment by simongeilfus** [comment]
Sorry guys! It took me an eternity to review this, ... sorry about that Hunter and thanks a lot for the modifications... 

I will probably make a few more changes, update the glNext branch and get the last version of imgui.

**Comment by brucelane** [comment]
for me, it's for the Cinder 0.8.6.. thank you Simon 
if possible with a sample

**Comment by simongeilfus** [comment]
Hi Bruce,
I'd be happy to accept pull request like this one (and try to merge them faster) in the future, but I'm probably not going to work on the 0.8.6 branch as cinder 0.9 should arrive fairly soon.

I'll try to work on a sample showing the very few methods/helpers I added in the wrapper, but in the meantime imgui samples are more relevant. I'm personally always using ImGui::ShowTestWindow when I'm looking for some sample code.

**Comment by brucelane** [comment]
hi Simon,
I'm working in my repo and I will maintain the 0.8.6 branch: https://github.com/brucelane/Cinder-ImGui/tree/Cinder-0.8.6.
I can do pull requests sometimes, if needed.
Don't bother creating samples, I found out with the help of Omar most of the answers
Thank you

**Comment by ocornut** [comment]
The 0.8.6 version doesn't bind the texture during render so functions like Image() don't work.

Compare
https://github.com/simongeilfus/Cinder-ImGui/blob/master/src/CinderImGui.cpp#L470

to 
https://github.com/simongeilfus/Cinder-ImGui/blob/Cinder-0.8.6/src/CinderImGui.cpp#L449

**Pull request merged**
