### PR TITLE
update imgui submodule to v1.46

### PR DESCRIPTION
**Pull request by brucelane**
added old samples

### CODE REVIEW

**Comment by simongeilfus** [comment]
Hey Bruce,
Thanks for the PR, I'd rather update the current sample with more examples. Those are quite old and don't really show more than [imgui_demo.cpp](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp) which is probably why I removed them in the first place.

**Comment by simongeilfus** [comment]
Any idea what's up with those 769 additions / 739 deletions in CinderImgui.cpp?

**Comment by brucelane** [comment]
hey Simon,
you can remove the samples, leaving only the basic one? 
769 additions / 739 deletions = visual studio formatting, sorry for that

**Comment by simongeilfus** [comment]
Woups, sorry Bruce, I totally missed out the fact your PR was for the 0.8.6 branch... 
I'm probably going to remove this branch as most people are going to move forward with the 0.9 release.

**Comment by brucelane** [comment]
yes it's for 0.8.6, but please keep it, I need it for my fork

**Pull request closed without merging**
