### PR TITLE
Updating to latest Cinder signals change, using ConnectionList

### PR DESCRIPTION
**Pull request by gaborpapp**
https://github.com/cinder/Cinder/pull/1676 broke the build. This is an attempt to fix it.

### CODE REVIEW

**Comment by simongeilfus** [comment]
Thanks for this!

**Comment by richardeakin** [comment]
Hm, this is odd that a `vector<signals::Connection>` broke? You _should_ be able to do this, and in fact `[ci::CameraUi(https://github.com/cinder/Cinder/blob/6456afd2fb6d7580f9892839ad7ef434d053faae/include/cinder/CameraUi.h#L103)` still does, which is why I don't understand how this was an issue. If it is a problem, ideally we'd fix it in `ci::signals`.

**Comment by gaborpapp** [comment]
as @notlion explained it in #32 the issue was that `signals::Connection` no longer had a copy-constructor.

**Comment by richardeakin** [comment]
Hm OK, we should probably get it reproduced in the unit tests then, and fix that. A `signals::Connection` should be copy-able (`signals::ScopedConnection` isn't). Though still don't understand how `CameraUi` is able to use `vector<Connection>::push_back()` but the code here broke.

**Pull request merged**
