### PR TITLE
Fix editor shortcuts on macOS; give Multiline editor more space

### PR DESCRIPTION
**Pull request by totalgee**
- set io.KeySuper properly in keyDown/Up callbacks, so that
  cut/copy/paste and other such functionality based on shortcut keys
  work on macOS.  KeySuper key is used by imgui to implement this
  functionality (in a special case for macOS) -- for other platforms
  KeyCtrl is used.
- allow more space in buffer for Multiline editor (previously, only
  128 new characters could be added or pasted into the editor each
  time it was active).
- eliminate unnecessary extra allocation in SetClipboardTextFn --
  imgui will now always send a zero-terminated string.

### CODE REVIEW

**Comment by totalgee** [comment]
This PR is to fix issues #65 and #66.

**Comment by totalgee** [comment]
BTW, I chose 16kb extra buffer space somewhat arbitrarily (it happens to be the size used by the buffer in the [imgui demo of InputTextMultiline](https://github.com/ocornut/imgui/blob/665bd1e140de3647d02b6c306b8ddb2d369e3f73/imgui_demo.cpp#L790)).  Also, you can see there is not really a better solution right now than just choosing some "good size", in this discussion: ocornut/imgui#1008.

**Comment by simongeilfus** [comment]
Thanks for this!

**Comment by totalgee** [comment]
Thank you for merging...that was quick!

**Pull request merged**
