### PR TITLE
Add boolean to access the drawData ( available only between Render() and NewFrame() )  

### PR DESCRIPTION
**Pull request by brucelane**
Added a mNewFrameInMainApp boolean to permit calling NewFrame() in the main app, not in CinderImGui, which permits to have access to the drawData ( available only between Render() and NewFrame() )  
To use it:
ui::initialize(ui::Options().NewFrameInMainApp(true));
It's false by default, so no problem with existing code using CinderImGui

### CODE REVIEW

**Comment by simongeilfus** [comment]
Hey Bruce,
Thanks for the PR. I've been planning to make the auto-render optional for a while. I've not run into any issue with the current design, but I can see it being annoying in some cases. 

I would do it the other way around though. Having a ```ui::Options::renderSignal``` or ```ui::Options::autoRender``` method and the corresponding bool living in the Options class (there's not really a point of making this bool static, and might be a problem in some cases). Imo a proper way to do it would be at initialisation, when reading the ```ui::Options```, subscribing to the desired signals.

Your second commit added a few undesired things and if I'm correct you seem to have rolled back imgui submodule to an older version.

Let me know what you think, I can try to make those changes today.

**Comment by brucelane** [comment]
hi Simon,
please use your way, it seems better, close my PR.
About the imgui submodule, please update to the latest version, there is a october 9th bug fix I need for the remoteImGui to work fine.
Thank you

**Comment by simongeilfus** [comment]
This should be addressed by this commit: https://github.com/simongeilfus/Cinder-ImGui/commit/b88b08ab31b315b1d1ea1f8900c1624e878b538d

Usage is the same as the one you suggested but the other way around semantically wise :
```c++
ui::initialize( ui::Options().autoRender( false ) );
```
After initialising the UI that way, you should call the ui::NewFrame and ui::Render yourself. By default they are called respectively right before the update and right after the draw.

Let me know if that works for you.

**Comment by brucelane** [comment]
works fine, thank you

**Pull request closed without merging**
